services:
  zero:
    command: dgraph zero --my=zero:5080 --replicas 3
    image: dgraph/dgraph:v22.0.2
    ports:
      - 5080:5080
      - 6080:6080
    volumes:
      - zero-data:/dgraph
  alpha1: &alpha
    command: dgraph alpha --my=alpha1:7080 --zero=zero:5080
    environment:
      DGRAPH_ALPHA_SECURITY: "whitelist=0.0.0.0/0"
    hostname: "alpha1"
    image: dgraph/dgraph:v22.0.2
    ports:
      - 8080:8080
      - 9080:9080
    volumes:
      - alpha1-data:/dgraph
  alpha2:
    <<: *alpha
    command: dgraph alpha --my=alpha2:7081 --zero=zero:5080 -o 1
    hostname: "alpha2"
    ports:
      - 8081:8081
      - 9081:9081
    volumes:
      - alpha2-data:/dgraph
  alpha3:
    <<: *alpha
    command: dgraph alpha --my=alpha3:7082 --zero=zero:5080 -o 2
    hostname: "alpha3"
    ports:
      - 8082:8082
      - 9082:9082
    volumes:
      - alpha3-data:/dgraph
  ratel:
    hostname: "ratel"
    # v20.7.0
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
volumes:
  alpha1-data:
  alpha2-data:
  alpha3-data:
  zero-data:
